app/models/comment.py
from . import ReprMixin
from . import Update
from . import db
import time


class Comment(db.Model, ReprMixin, Update):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String())
    created_time = db.Column(db.Integer, default=0)
    post_user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comment_tweet_id = db.Column(db.Integer, db.ForeignKey('tweets.id'))

    def __init__(self, form):
        print('comment init', form)
        content = form.get('content', '')
        self.content = content
        self.created_time = int(time.time())

    def json(self):
        self.id
        extra = dict(
            post_user_id=self.post_user_id,
            comment_tweet_id=self.comment_tweet_id,
            type='comment',
        )
        d = {k:v for k,v in self.__dict__.items() if k not in self.blacklist()}
        d.update(extra)
        return d

    def blacklist(self):
        b = [
            '_sa_instance_state',
        ]
        return b

app/controllers/__init__.py
from flask import redirect
from flask import url_for
from flask import render_template
from flask import session
from flask import Blueprint
from flask import abort

from ..models import User
from ..models import Tweet


main = Blueprint('controllers', __name__)


# 通过 session 来获取当前登录的用户
def current_user():
    # print('session, debug', session.permanent)
    username = session.get('username', '')
    u = User.query.filter_by(username=username).first()
    return u


@main.route('/')
def index():
    view = 'auth.login_view'
    return redirect(url_for(view))


@main.route('/tweet')
def timeline_view():
    u = current_user()
    all_tweets = Tweet.query.all()
    all_tweets.sort(key=lambda t: t.created_time, reverse=True)
    return render_template('timeline.html', user=u, all_tweets=all_tweets)


@main.route('/timeline')
def mytweet_view():
    u = current_user()
    all_tweets = u.tweets
    all_tweets.sort(key=lambda t: t.created_time, reverse=True)
    return render_template('mytweet.html', user=u, all_tweets=all_tweets)


@main.route('/timeline/<username>')
def other_tweet_view(username):
    user = User.query.filter_by(username=username).first_or_404()
    view_user = current_user()
    all_tweets = user.tweets
    all_tweets.sort(key=lambda t: t.created_time, reverse=True)
    return render_template('othertweet.html', user=user, view_user=view_user, all_tweets=all_tweets)



@main.route('/tweet/update/<tweet_id>')
def tweet_update_view(tweet_id):
    one_tweet = Tweet.query.filter_by(id=tweet_id).first_or_404()
    data_u = one_tweet.user
    cur_u = current_user()
    if data_u != cur_u:
        abort(401)
    else:
        return render_template('tweet_update.html', tweet=one_tweet, user=current_user())


@main.route('/tweet/comments/<tweet_id>')
def comments_view(tweet_id):
    view_user = current_user()
    one_tweet = Tweet.query.filter_by(id=tweet_id).first()
    user = one_tweet.user
    comments = one_tweet.comments
    comments.sort(key=lambda t: t.created_time, reverse=True)
    return render_template('comments.html', user=user, view_user = view_user, one_tweet=one_tweet, comments=comments)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
{% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}

    {% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/blog-home.css" rel="stylesheet">

        <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
{% endblock %}
</head>


<body>
{% block navbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('controllers.timeline_view',username=user.username) }}">StArt Tweet</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ url_for('controllers.timeline_view',username=user.username) }}">首页</a>
                    </li>
                    <li>
                        <a href="{{ url_for('controllers.mytweet_view')}}">我的微博</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}

            {% endblock %}
            </div>
            <!-- Blog Sidebar profile Column -->
            <div class="col-md-4 sidebar_affix" >

                {% block sidebar %}
                <div class="well" data-username = "{{ user.username }}">
                    <h3>您的用户名：{{ user.username }}</h3>
                    <h4>关注用户：0(todo)</h4>
                    <h4>粉丝：0(todo)</h4>
                    <p>个性签名：(todo)</p>
                </div>
                {% endblock %}
            </div>


        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            {% block footer %}
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; StArt Tweet 2017</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            {% endblock %}
        </footer>

    </div>
    <!-- /.container -->

</body>

</html>

app/templates/comments.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
{% block head %}
    {{ super() }}
    <script src="/static/js/jquery.tmpl.min.js"></script>
    <script src="/static/js/weibo.js"></script>
    <script src="/static/js/action.js"></script>
    <script>
        var commentTemplate = function (comment) {
            log('debug tweet', comment);
            var c = comment;
            var username = c.username;
            var content = c.content;
            var created_time = c.created_time;
            var othertweet_view_url = c.othertweet_view_url;
            var parsed_time = longTimeAgo(created_time);
            var temp = `
                <div class="id-one-comment">
                    <p class="comment">
                        <a href="${othertweet_view_url}">${username}</a>
                        于<time class="glyphicon glyphicon-time" data-time="${created_time}">${parsed_time}</time>说：
                    </p>
    {#                <hr>#}
    {#                <img class="img-responsive" src="#" alt="">#}
                    <p><h4>${content}</h4></p>
                    <hr>
                </div>
            `;
            return temp;
        };

        var insertComments = function (Comments) {
{#            for(var i=Comments.length-1; i>-1; i--){#}
            for(var i=0; i<Comments.length; i++){
                var Comment = Comments[i];
                var t = commentTemplate(Comment);
                $('#id-comment-title').after(t);
            }
        };
{#        把图片功能加了，#}
{#        灌10个假用户，#}
{#        灌100条假数据，#}

        var loadComments = function () {
            var form = {
                'id':$("#id-content-comment").data('id')
            };
            weibo.get_comments(form, function (r) {
                log('tweets get',r.success);
                if(r.success){
                    var Comments = r.data;
                    insertComments(Comments);
                }else{
                    log(r.message);
                }
            })
        };
    
    
        $(document).ready(function(){
            var div = $("time");
            var unixTime = div.data('time');
{#            log('debug unixtime', unixTime);#}
            var time = longTimeAgo(unixTime);
{#            log('debug time', time);#}
            div.text(time);
            loadComments();
            bindAddCommentAction();
        });
    </script>
    {% block title %}
        <title>comments</title>
    {% endblock %}
{% endblock %}
</head>
<body>
    {% block content %}
        <!-- Blog Entries Column -->
    <h1 class="page-header">
        评论
        <small>随便说点什么吧</small>
    </h1>
    <p class="lead" id="id-content-comment" data-id="{{ one_tweet.id }}">
        <a href="{{ url_for('controllers.other_tweet_view', username=one_tweet.user.username) }}">{{ one_tweet.user.username }}</a>
        于<time class="unixtime" id='id-unixtime' data-time="{{ one_tweet.created_time }}"></time>说：
    </p>
{#    <hr>#}
    <div>
        <h3>{{ one_tweet.content }}</h3>
    </div>
    <hr>
    <div class="well">
        <h4>评论在下方:</h4>
        <div class="form-group"><textarea class="form-control" rows="5" id="id-input-content" name="content" placeholder="评论点什么"></textarea>
        </div>
        <button type="button" id="id-button-add" class="btn btn-primary">提交评论</button>
    </div>
    <h3 id="id-comment-title">所有评论：</h3>


    <!-- Pager -->
{#    <ul class="pager">#}
{#        <li class="previous">#}
{#            <a href="#">&larr; Newer</a>#}
{#        </li>#}
{#        <li class="next">#}
{#            <a href="#">Older &rarr;</a>#}
{#        </li>#}
{#    </ul>#}
    {% endblock %}

</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Welcome to StArt！</title>
    <link rel="stylesheet" href="/static/css/login.css">
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script src="/static/js/weibo.js"></script>
    <script src="/static/js/login.js"></script>
    <script>
        // setup
        var setup = function () {
            // tab click
            $('.gua-tab > a').on('click', function () {
                var self = $(this);
                $('.active').removeClass('active');
                self.addClass('active');
            });

            // tab action
            var tabAction = function (position, showLogin) {
                $(".gua-block").animate({
                    "left": position
                }, "fast");
                $('#id-div-login').toggle(showLogin);
                $('#id-div-signup').toggle(!showLogin);
            };

            $('#id-a-signup').on('click', function () {
                var position = '100px';
                var showLogin = false;
                tabAction(position, showLogin);
            });

            $('#id-a-login').on('click', function () {
                var position = '155px';
                var showLogin = true;
                tabAction(position, showLogin);
            });

            // select signup
            $('#id-a-login').click();
        };

        var bindActions = function () {
            $('#id-button-register').on('click', function () {
                // 这个函数的定义在 login.js 里面
                // js 就是可以这样随性地用
                register();
            });

            $('#id-button-login').on('click', function () {
                login();
            });
        };

        var __main = function () {
            setup();
            bindActions();
        };

        $(document).ready(function () {
            __main();
        });
    </script>
</head>
<body>
<div class="gua-container">
    <div class="gua-main">
        <div class="gua-header">
            <h1 class="gua-title">StArt</h1>
            <h2 class="gua-subtitle">清真 AJAX 博客</h2>
        </div>
        <div class="gua-form">
            <div class="gua-tab">
                <a id="id-a-signup" href="#">注册</a>
                <a id="id-a-login" href="#">登录</a>
                <div class="gua-block"></div>
            </div>
            <div id="id-div-signup">
                <div class="gua-form-textinput">
                    <div class="gua-input-wrapper">
                        <input id="id-input-username" type="text" placeholder="用户名（不少于 3 位）" required/>
                    </div>
                    <div class="gua-input-wrapper">
                        <input id="id-input-password" type="text" placeholder="密码（不少于 3 位）" required/>
                    </div>
                </div>
                <button id="id-button-register" class="gua-button-big">注册</button>
            </div>
            <div id="id-div-login">
                <div class="gua-form-textinput">
                    <div class="gua-input-wrapper">
                        <input id="id-input-login-username" type="text" placeholder="用户名" required/>
                    </div>
                    <div class="gua-input-wrapper">
                        <input id="id-input-login-password" type="text" placeholder="密码" required/>
                    </div>
                </div>
                <button id="id-button-login" class="gua-button-big" type="submit">进入</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/templates/mytimeline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>myTweet</title>
    <script src="/static/jquery-3.0.0.min.js"></script>
    <script src="/static/jquery.tmpl.min.js"></script>
    <script src="/static/weibo.js"></script>
    <script src="/static/action.js"></script>
    <script id="id-template-tweet" type="text/x-jquery-tmpl">
         <p>
            ${ content } : ${ created_time }
            <a href="tweet/update/${ id }">编辑</a>
            <button class="button-delete" data-id="${ id }" >删除</button>
         </p>
    </script>
    <script>
        $(document).ready(function(){
            bindDeleteAction();
            bindAddTweetAction('#id-button-add');
        });
    </script>
</head>
<body>
    <P>
        您的用户名：{{ user.username }}
        关注用户：0
        粉丝：0
        <a href="/mytweet/{{ user.username }}">我的微博</a>
        <a href="{{ url_for('timeline',username=user.username) }}">返回首页</a>
    </P>
    <div>
        <textarea id="id-input-content" name="content" placeholder="写点东西"></textarea>
        <br>
        <button id="id-button-add">添加微博</button>
    </div>
    {% for t in all_tweets %}
    <p>
        {{ t.content }} : {{ t.created_time }}
{#        <a href="{{url_for('tweet_update_view', tweet_id=t.id)}}">编辑</a>#}
        <a href="/tweet/update/{{t.id}}">编辑</a>
        <button class="button-delete" data-id="{{ t.id }}">删除</button>
        <br>
        <a href="/tweet/comments/{{ t.id }}">评论({{ t.comments|length }})</a>
    </p>
    {% endfor %}
</body>
</html>

app/templates/mytweet.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block head %}
    {{ super() }}
    <script src="/static/js/jquery.tmpl.min.js"></script>
    <script src="/static/js/weibo.js"></script>
    <script src="/static/js/action.js"></script>
    <script>
        var tweetTemplate = function (tweet) {
            log('debug tweet', tweet);
            var t = tweet;
            var id = t.id
            var username = t.username;
            var content = t.content;
            var created_time = t.created_time;
            var comments_lenth = t.comments_lenth;
            var othertweet_view_url = t.othertweet_view_url;
            var tweet_comment_url = t.tweet_comment_url;
            var parsed_time = longTimeAgo(created_time);
            var temp = `
                <div class="id-one-tweet">
                    <p class="lead">
{#                        <a href="${othertweet_view_url}">${username}</a>#}
                        我于<time data-time="${created_time}">${parsed_time}</time>说：

                    </p>
    {#                <hr>#}
    {#                <img class="img-responsive" src="#" alt="">#}
{#                    <br>#}
                    <p>
                        <h3>${content}</h3>
                        <a href="/tweet/update/${id}">编辑</a>
                        <button class="button-delete" data-id="${ id }" >删除</button>
                    </p>
                    <span><a class="id-commmets" href="${tweet_comment_url}">查看评论(${comments_lenth})</a></span>
                    <hr>
                </div>
            `;
            return temp;
        };


        var insertTweets = function (tweets) {
            for(var i=tweets.length-1; i>-1; i--){
                var tweet = tweets[i];
{#                log('tweet ', tweet);#}
                var t = tweetTemplate(tweet);
{#                log('temp', t);#}
                $('.col-md-8').append(t);
{#                log('append success');#}
            }
        };


        var loadUserTweets = function () {
            form = {
                'username': $(".well").data('username')
            };
            log('debug form',form);
            weibo.get_user_tweets(form, function (r) {
                log('tweets get',r.success);
                if(r.success){
                    var tweets = r.data;
                    insertTweets(tweets);
                }else{
                    log(r.message);
                }
            })
        }
    </script>
    <script>
        $(document).ready(function(){
            loadUserTweets();
            bindDeleteAction();
            bindAddTweetAction('.page-header');
        });
    </script>
    {% block title %}
        <title>mytweet</title>
    {% endblock %}
{% endblock %}
</head>
<body>
{% block content %}
        <!-- Blog Entries Column -->
    <h1 class="page-header">
        我的主页
        <small>我的微博</small>
    </h1>
{#    {% for t in all_tweets %}#}
{#    <!-- First Blog Post -->#}
{#    <div class="content">#}
{#    <br>#}
{#        <p class="lead">#}
{#            <a href="{{ url_for('controllers.other_tweet_view', username=t.user.username) }}">{{ t.user.username }}</a>#}
{#        </p>#}
{#        <p><span class="glyphicon glyphicon-time"></span> {{ t.created_time }}</p>#}
{#        <hr>#}
{#        <div>#}
{#            {{ t.content }}#}
{#            <a href="/tweet/update/{{t.id}}">编辑</a>#}
{#            <button class="button-delete" data-id="{{ t.id }}">删除</button>#}
{#            <a href="/tweet/comments/{{ t.id }}"><h4>评论({{ t.comments|length }})</h4></a>#}
{#        </div>#}
{#        <hr>#}
{#    </div>#}
{#    {% endfor %}#}
    <!-- Second Blog Post -->



    <!-- Pager -->
{#    <ul class="pager">#}
{#        <li class="previous">#}
{#            <a href="#">&larr; Newer</a>#}
{#        </li>#}
{#        <li class="next">#}
{#            <a href="#">Older &rarr;</a>#}
{#        </li>#}
{#    </ul>#}
{% endblock %}

    {% block sidebar %}
        {{ super() }}
        <!-- Blog Input Well -->
        <div class="well">
            <h4>说点新鲜事？</h4>
            <div>
                <textarea class="form-control" id="id-input-content" name="content" placeholder="写点东西" rows="6"></textarea>
            </div>
            <br>
            <div align="right">
                <button type="button" class="btn btn-primary btn-lg" id="id-button-add">
                    发！
                </button>
            </div>
        </div>
    {% endblock %}
</body>
</html>

app/templates/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}</title>
</head>
<body>
    <P>
        您的用户名：{{ view_user.username }}
        关注用户：0
        粉丝：0
        <a href="/mytweet/{{ view_user.username }}">我的微博</a>
        <a href="{{ url_for('timeline',username=view_user.username) }}">返回首页</a>
    </P>

    <h3 id="id-tweet-title">{{ user.username }}的所有微博</h3>
    {% for t in all_tweets %}
    <p>
        <a href="{{ url_for('other_user_view', username=t.user.username) }}">{{ t.user.username }}</a>        {{ t.content }}
        {{ t.created_time }}
    </p>
    <a href="/tweet/comments/{{ t.id }}">评论({{ t.comments|length }})</a>
{#    <!--{{ t.comments|length }} 就是求对象的长度，等价于python中len(t.comments)-->#}
    {% endfor %}
</body>
</html>

app/templates/othertweet.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block head %}
    {{ super() }}
    <script src="/static/js/jquery.tmpl.min.js"></script>
    <script src="/static/js/weibo.js"></script>
    <script src="/static/js/action.js"></script>
    <script>
        var tweetTemplate = function (tweet) {
            log('debug tweet', tweet);
            var t = tweet;
            var id = t.id
            var username = t.username;
            var content = t.content;
            var created_time = t.created_time;
            var comments_lenth = t.comments_lenth;
            var othertweet_view_url = t.othertweet_view_url;
            var tweet_comment_url = t.tweet_comment_url;
            var parsed_time = longTimeAgo(created_time);
            var temp = `
                <div class="id-one-tweet">
                    <p class="lead">
{#                        <a href="${othertweet_view_url}">${username}</a>#}
                        他于<time data-time="${created_time}">${parsed_time}</time>说：

                    </p>
    {#                <hr>#}
    {#                <img class="img-responsive" src="#" alt="">#}
{#                    <br>#}
                    <p>
                        <h3>${content}</h3>
{#                        <a href="/tweet/update/${id}">编辑</a>#}
{#                        <button class="button-delete" data-id="${ id }" >删除</button>#}
                    </p>
                    <span><a class="id-commmets" href="${tweet_comment_url}">查看评论(${comments_lenth})</a></span>
                    <hr>
                </div>
            `;
            return temp;
        };


        var insertTweets = function (tweets) {
            for(var i=tweets.length-1; i>-1; i--){
                var tweet = tweets[i];
{#                log('tweet ', tweet);#}
                var t = tweetTemplate(tweet);
{#                log('temp', t);#}
                $('.col-md-8').append(t);
{#                log('append success');#}
            }
        };


        var loadUserTweets = function () {
            form = {
                'username': $(".page-header").data('username')
            };
            log('debug form',form);
            weibo.get_user_tweets(form, function (r) {
                log('tweets get',r.success);
                if(r.success){
                    var tweets = r.data;
                    insertTweets(tweets);
                }else{
                    log(r.message);
                }
            })
        }
    </script>
    <script>
        $(document).ready(function(){
            loadUserTweets();
            bindDeleteAction();
            bindAddTweetAction('.page-header');
        });
    </script>
    {% block title %}
        <title>mytweet</title>
    {% endblock %}
{% endblock %}
</head>
<body>
{% block content %}
        <!-- Blog Entries Column -->
    <h1 class="page-header" data-username="{{ all_tweets[0].user.username }}">
        他的主页
        <small>他的微博</small>
    </h1>
{#    {% for t in all_tweets %}#}
{#    <!-- First Blog Post -->#}
{#    <br>#}
{#    <p class="lead">#}
{#        <a href="{{ url_for('controllers.other_tweet_view', username=t.user.username) }}">{{ t.user.username }}</a>#}
{#    </p>#}
{#    <p><span class="glyphicon glyphicon-time"></span> {{ t.created_time }}</p>#}
{#    <hr>#}
{#    <div>#}
{#        {{ t.content }}#}
{#        <a href="/tweet/comments/{{ t.id }}"><h4>评论({{ t.comments|length }})</h4></a>#}
{#    </div>#}
{#    <a class="btn btn-primary" href="{{ url_for('controllers.other_tweet_view', username=all_tweets[0].user.username) }}">看看他的微博 <span class="glyphicon glyphicon-chevron-right"></span></a>#}
{#    <hr>#}
{#    {% endfor %}#}
    <!-- Second Blog Post -->



    <!-- Pager -->
{#    <ul class="pager">#}
{#        <li class="previous">#}
{#            <a href="#">&larr; Newer</a>#}
{#        </li>#}
{#        <li class="next">#}
{#            <a href="#">Older &rarr;</a>#}
{#        </li>#}
{#    </ul>#}
    {% endblock %}

    {% block sidebar %}
        {{ super() }}
        <!-- Blog Input Well -->
    {% endblock %}
</body>
</html>

app/templates/timeline.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
{% block head %}
    {{ super() }}
    <script src="/static/js/jquery.tmpl.min.js"></script>
    <script src="/static/js/weibo.js"></script>
    <script src="/static/js/action.js"></script>
    <script>
        var tweetTemplate = function (tweet) {
            log('debug tweet', tweet);
            var t = tweet;
            var username = t.username;
            var content = t.content;
            var created_time = t.created_time;
            var comments_lenth = t.comments_lenth;
            var othertweet_view_url = t.othertweet_view_url;
            var tweet_comment_url = t.tweet_comment_url;
            var parsed_time = longTimeAgo(created_time)
            var temp = `
                <div class="id-one-tweet">
                    <p class="lead">
                        <a href="${othertweet_view_url}">${username}</a>
                        于<time data-time="${created_time}">${parsed_time}</time>说：
                    </p>

{#                    <time data-time="1468735815">13 天前</time>#}
    {#                <hr>#}
    {#                <img class="img-responsive" src="#" alt="">#}
{#                    <hr>#}
                    <h3><p>${content}</p></h3>
                    <span><a class="id-commmets" href="${tweet_comment_url}">评论(${comments_lenth})</a></span><br>
                    <br>
{#                    <hr>#}
                    <a class="btn btn-primary" href="${othertweet_view_url}">看看他的其他微博<span class="glyphicon glyphicon-chevron-right"></span></a>
                    <hr>
                </div>
            `;
            return temp;
        };

        var insertTweets = function (tweets) {
            for(var i=tweets.length-1; i>-1; i--){
                var tweet = tweets[i];
{#                log('tweet ', tweet);#}
                var t = tweetTemplate(tweet);
{#                log('temp', t);#}
                $('.col-md-8').append(t);
{#                log('append success');#}
            }
        };

        var loadTweets = function () {
            weibo.get_all_tweets(function (r) {
                log('tweets get',r.success);
                if(r.success){
                    var tweets = r.data;
                    insertTweets(tweets);
                }else{
                    log(r.message);
                }
            })
        };


        $(document).ready(function(){
            loadTweets();
            bindAddTweetAction('.page-header');
        });
    </script>
    {% block title %}
        <title>timeline</title>
    {% endblock %}
{% endblock %}
<body>
    {% block content %}
        <!-- Blog Entries Column -->
    <h1 class="page-header">
        首页
        <small>所有人的微博</small>
    </h1>
{#    {% for t in all_tweets %}#}
{#    <!-- First Blog Post -->#}
{#    <br>#}
{#    <p class="lead">#}
{#        <a href="{{ url_for('controllers.other_tweet_view', username=t.user.username) }}">{{ t.user.username }}</a>#}
{#    </p>#}
{#    <p><span class="glyphicon glyphicon-time"></span> {{ t.created_time }}</p>#}
{#    <hr>#}
{#    <div>#}
{#        <h3>{{ t.content }}</h3>#}
{#        <a href="/tweet/comments/{{ t.id }}"><h4>评论({{ t.comments|length }})</h4></a>#}
{#    </div>#}
{#    <a class="btn btn-primary" href="{{ url_for('controllers.other_tweet_view', username=all_tweets[0].user.username) }}">看看他的微博 <span class="glyphicon glyphicon-chevron-right"></span></a>#}
{#    <hr>#}
{#    {% endfor %}#}
    <!-- Second Blog Post -->


{#    todo:增加翻页功能#}
    <!-- Pager -->
{#    <ul class="pager">#}
{#        <li class="previous">#}
{#            <a href="#">&larr; Newer</a>#}
{#        </li>#}
{#        <li class="next">#}
{#            <a href="#">Older &rarr;</a>#}
{#        </li>#}
{#    </ul>#}
    {% endblock %}

    {% block sidebar %}
        {{ super() }}
        <!-- Blog Input Well -->
        <div class="well">
            <h4>说点新鲜事？</h4>
            <div>
                <textarea class="form-control" id="id-input-content" name="content" placeholder="写点东西" rows="6"></textarea>
            </div>
            <br>
            <div align="right">
                <button type="button" class="btn btn-primary btn-lg" id="id-button-add">
                    发！
                </button>
            </div>
        </div>
    {% endblock %}
</body>
</html>

app/templates/tweet_update.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
<head>
    {% block head %}
    {{ super() }}
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script src="/static/js/jquery.tmpl.min.js"></script>
    <script src="/static/js/weibo.js"></script>
    <script src="/static/js/action.js"></script>
    <script>
        $(document).ready(function (){
            log("ready");
            bindUpdateTweetAction()
        });
    </script>
        {% block title %}
        <title>修改微博</title>
        {% endblock %}
    {% endblock %}
</head>
<body>
    {% block content %}
    <div class="well">
        <h4>修改成:</h4>
        <div class="form-group">
            <textarea class="form-control" rows="5" id="id-input-content" name="content" data-id="{{ tweet.id }}" placeholder="{{ tweet.content }}"></textarea>
        </div>
        <button id="id-button-submit" type="button" class="btn btn-primary">提交修改</button>
    </div>
    {% endblock %}
</body>
</html>